"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { CustomerReportPayload } from "@/lib/reportTypes";

type ReportCustomer = {
  id: string;
  name: string;
  phone: string | null;
  email: string | null;
} | null;

type ReportLead = {
  id: string;
  customer_id: string | null;
  customer_name: string;
  status: "NEW" | "CONTACTED" | "NEGOTIATING" | "WON" | "LOST";
  follow_up_date: string | null;
  vehicle_id: string | null;
} | null;

type ReportSalesperson = {
  id: string;
  name: string | null;
  email: string | null;
} | null;

type Report = {
  id: string;
  vehicle_id: string;
  customer_id: string | null;
  lead_id: string | null;
  created_by: string | null;
  share_token: string | null;
  created_at: string;
  customer_report: CustomerReportPayload;
  customer: ReportCustomer;
  lead: ReportLead;
  salesperson: ReportSalesperson;
};

type ReportsResponse = {
  success: boolean;
  reports?: Report[];
  error?: string;
};

function formatDate(value: string | null | undefined) {
  if (!value) return "N/A";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "N/A";
  }

  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatDateTime(value: string | null | undefined) {
  if (!value) return "N/A";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "N/A";
  }

  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function statusClasses(status: string | null | undefined) {
  switch (status) {
    case "NEW":
      return "bg-blue-50 text-blue-700 ring-blue-200";
    case "CONTACTED":
      return "bg-yellow-50 text-yellow-700 ring-yellow-200";
    case "NEGOTIATING":
      return "bg-purple-50 text-purple-700 ring-purple-200";
    case "WON":
      return "bg-green-50 text-green-700 ring-green-200";
    case "LOST":
      return "bg-red-50 text-red-700 ring-red-200";
    default:
      return "bg-gray-100 text-gray-600 ring-gray-200";
  }
}

export default function ReportsClient() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [userRole, setUserRole] = useState<string | null>(null);

  const loadReports = useCallback(async () => {
    try {
      setLoading(true);
      setError("");

      const response = await fetch("/api/reports", {
        cache: "no-store",
      });

      const result: ReportsResponse = await response.json();

      if (!response.ok || !result.success) {
        throw new Error(
          result.error || "Failed to load reports."
        );
      }

      setReports(result.reports ?? []);
    } catch (err) {
      console.error("Reports loading error:", err);

      setError(
        err instanceof Error
          ? err.message
          : "Failed to load reports."
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const timeoutId = window.setTimeout(() => {
      void loadReports();
    }, 0);

    return () => {
      window.clearTimeout(timeoutId);
    };
  }, [loadReports]);

  useEffect(() => {
    async function checkRole() {
      try {
        const response = await fetch("/api/auth/session");
        const data = await response.json();
        setUserRole(data.profile?.role || null);
      } catch (err) {
        console.error("Failed to check user role:", err);
      }
    }
    checkRole();
  }, []);

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto">
      <p className="text-xs font-medium text-neutral-500">
        Vehicle Intelligence
      </p>

      <div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-xl font-semibold text-neutral-900">
            Reports
          </h1>

          <p className="mt-1 text-xs text-neutral-600">
            Customer reports generated by your sales team.
          </p>
        </div>

        {!loading && !error && (
          <div className="rounded-md border border-neutral-200 bg-white px-3 py-2 shadow-sm">
            <p className="text-[10px] font-medium uppercase tracking-wide text-neutral-500">
              Total Reports
            </p>

            <p className="mt-1 text-lg font-bold text-neutral-900">
              {reports.length}
            </p>
          </div>
        )}
      </div>

      {loading && (
        <div className="mt-6 rounded-lg border border-neutral-200 bg-white p-6 text-center shadow-sm">
          <p className="text-xs font-medium text-neutral-700">
            Loading reports...
          </p>
        </div>
      )}

      {!loading && error && (
        <div className="mt-6 rounded-lg border border-red-200 bg-white p-4 shadow-sm">
          <h2 className="text-xs font-semibold text-neutral-900">
            Unable to load reports
          </h2>

          <p className="mt-1 text-xs text-red-600">
            {error}
          </p>

          <button
            type="button"
            onClick={() => void loadReports()}
            className="mt-3 rounded-md bg-black px-3 py-1.5 text-xs font-semibold text-white hover:bg-neutral-800"
          >
            Try Again
          </button>
        </div>
      )}

      {!loading && !error && reports.length === 0 && (
        <div className="mt-6 rounded-lg border border-neutral-200 bg-white p-8 text-center shadow-sm">
          <h2 className="text-xs font-semibold text-neutral-900">
            No reports yet
          </h2>

          <p className="mt-2 text-xs text-neutral-500">
            Reports generated by your sales team will appear here.
          </p>
        </div>
      )}

      {!loading && !error && reports.length > 0 && (
        <div className="mt-6 space-y-3">
          {reports.map((report) => {
            const customerReport =
              report.customer_report ??
              ({} as CustomerReportPayload);

            const vehicle = customerReport.vehicle ?? {
              year: null,
              make: null,
              model: null,
              trim: null,
              vin: "",
            };

            const historyHighlights =
              customerReport.history_highlights ?? {
                theft_found: false,
                odometer_available: false,
              };

            const title = [
              vehicle.year,
              vehicle.make,
              vehicle.model,
              vehicle.trim,
            ]
              .filter(
                (value) =>
                  value !== null &&
                  value !== undefined &&
                  String(value).trim() !== ""
              )
              .join(" ");

            const active = Boolean(report.share_token);

            const reportUrl = report.share_token
              ? `/report/${encodeURIComponent(
                  report.share_token
                )}`
              : null;

            return (
              <div
                key={report.id}
                className="overflow-hidden rounded-lg border border-neutral-200 bg-white shadow-sm"
              >
                <div className="flex flex-col gap-4 p-4 lg:flex-row lg:items-start lg:justify-between">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <h2 className="text-sm font-semibold text-neutral-900">
                        {title || "Vehicle"}
                      </h2>

                      {historyHighlights.theft_found && (
                        <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-medium text-amber-700 ring-1 ring-amber-200">
                          Theft record
                        </span>
                      )}

                      {!historyHighlights.theft_found &&
                        historyHighlights.odometer_available && (
                          <span className="rounded-full bg-green-50 px-2 py-0.5 text-[10px] font-medium text-green-700 ring-1 ring-green-200">
                            Odometer records
                          </span>
                        )}

                      {!active && (
                        <span className="rounded-full bg-neutral-100 px-2 py-0.5 text-[10px] font-medium text-neutral-500 ring-1 ring-neutral-200">
                          Revoked
                        </span>
                      )}
                    </div>

                    <p className="mt-1 break-all font-mono text-[10px] text-neutral-400">
                      VIN: {vehicle.vin || "N/A"}
                    </p>

                    <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
                      <div className="rounded-md border border-neutral-200 bg-neutral-50 p-2">
                        <p className="text-[10px] font-medium uppercase tracking-wide text-neutral-500">
                          Customer
                        </p>

                        <p className="mt-1 truncate text-xs font-semibold text-neutral-900">
                          {report.customer?.name || "No customer"}
                        </p>

                        {report.customer?.phone && (
                          <p className="mt-1 truncate text-[10px] text-neutral-500">
                            {report.customer.phone}
                          </p>
                        )}

                        {!report.customer?.phone &&
                          report.customer?.email && (
                            <p className="mt-1 truncate text-[10px] text-neutral-500">
                              {report.customer.email}
                            </p>
                          )}
                      </div>

                      <div className="rounded-md border border-neutral-200 bg-neutral-50 p-2">
                        <p className="text-[10px] font-medium uppercase tracking-wide text-neutral-500">
                          Lead
                        </p>

                        <div className="mt-1 flex flex-wrap items-center gap-2">
                          <p className="truncate text-xs font-semibold text-neutral-900">
                            {report.lead?.customer_name ||
                              report.customer?.name ||
                              "No lead"}
                          </p>

                          {report.lead?.status && (
                            <span
                              className={`rounded-full px-2 py-0.5 text-[10px] font-medium ring-1 ${statusClasses(
                                report.lead.status
                              )}`}
                            >
                              {report.lead.status}
                            </span>
                          )}
                        </div>

                        {report.lead?.follow_up_date && (
                          <p className="mt-1 text-[10px] text-neutral-500">
                            Follow-up:{" "}
                            {formatDate(
                              report.lead.follow_up_date
                            )}
                          </p>
                        )}
                      </div>

                      <div className="rounded-md border border-neutral-200 bg-neutral-50 p-2">
                        <p className="text-[10px] font-medium uppercase tracking-wide text-neutral-500">
                          Salesperson
                        </p>

                        <p className="mt-1 truncate text-xs font-semibold text-neutral-900">
                          {report.salesperson?.name ||
                            "Unknown"}
                        </p>

                        {report.salesperson?.email && (
                          <p className="mt-1 truncate text-[10px] text-neutral-500">
                            {report.salesperson.email}
                          </p>
                        )}
                      </div>

                      <div className="rounded-md border border-neutral-200 bg-neutral-50 p-2">
                        <p className="text-[10px] font-medium uppercase tracking-wide text-neutral-500">
                          Generated
                        </p>

                        <p className="mt-1 text-xs font-semibold text-neutral-900">
                          {formatDate(report.created_at)}
                        </p>

                        <p className="mt-1 text-[10px] text-neutral-500">
                          {formatDateTime(report.created_at)}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className="flex shrink-0 flex-wrap gap-2 lg:w-auto lg:flex-col">
                    {userRole !== "customer" && (
                      <Link
                        href={
                          vehicle.vin
                            ? `/vehicles/${encodeURIComponent(
                                vehicle.vin
                              )}`
                            : "/vehicles"
                        }
                        className="inline-flex items-center justify-center rounded-md border border-neutral-300 px-3 py-1.5 text-xs font-semibold text-neutral-700 hover:bg-neutral-50"
                      >
                        Vehicle Page
                      </Link>
                    )}

                    {active && reportUrl && (
                      <Link
                        href={reportUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center justify-center rounded-md bg-black px-3 py-1.5 text-xs font-semibold text-white hover:bg-neutral-800"
                      >
                        View Report
                      </Link>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
